package djun.com.br.com.djun;

/**
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {
    public static void main(String[] args){
        System.out.print(new Problem2().getValueFromFibonacciPosition(3));
    }

    public long getValueFromFibonacciPosition(long position){
        long[] aux = {1,2};
        if(position <= 2 ){
            return aux[(int)position-1];
        }


        return 0;
    }
}
