package br.com.djun.dojo;

import org.junit.Assert;
import org.junit.Test;

/**
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2Test {
    private Problem2 problem2;

    public Problem2Test(){
        problem2 = new Problem2();
    }

    @Test
    public void getSum1(){
        Assert.assertEquals(0,problem2.getSum(1));
    }

    @Test
    public void getSum2(){
        Assert.assertEquals(2,problem2.getSum(2));
    }

    @Test
    public void getSum3(){
        Assert.assertEquals(2,problem2.getSum(3));
    }

    @Test
    public void getSum80(){
        Assert.assertEquals(44,problem2.getSum(80));
    }

    @Test
    public void getSum100(){
        Assert.assertEquals(44,problem2.getSum(100));
    }
}
