package br.com.djun.dojo;

import org.junit.Assert;
import org.junit.Test;

/**
 The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?
 */
public class Problem12Test {
    private Problem12 p;

    public Problem12Test(){
        p = new Problem12();
    }
    @Test
    public void getFirstTriangleNumberToHaveOver(){
        Assert.assertEquals(3, p.getFirstTriangleNumberToHaveOver(2));
        Assert.assertEquals(6, p.getFirstTriangleNumberToHaveOver(4));
        Assert.assertEquals(28, p.getFirstTriangleNumberToHaveOver(5));
    }
}
