package br.com.djun.dojo;

/**
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {
    public static void main(String[] args){
        System.out.println(new Problem2().getSum(4000000));
    }

    public long getSum(long limit){
        if(limit == 1){
            return 0;
        }
        if(limit == 2){
            return 2;
        }

        long[] aux = {1,2,0};
        long count = 2;

        while(true) {
            aux[2] = aux[0] + aux[1];

            if(aux[2] > limit){
                break;
            }
            if(aux[2] % 2 == 0) {
                count += aux[2];
            }
            aux[0] = aux[1];
            aux[1] = aux[2];
        }

        return count;
    }
}